---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# Image will be published to ghcr.io/<user>/<name>.
name: atomic-kokoriko

# Description will be included in the image's metadata.
description: "Sway Atomic + minimal host + Toolbox dev stack (Rust/.NET/Node) with Helix & Nushell"

# The base image to build on top of (FROM) and the version tag to use.
base-image: ghcr.io/ublue-os/sway-atomic-main
image-version: latest # Or pin "42" for Fedora 42.

# Module configuration, executed in order you can include multiple instances of the same module.
modules:
  # # Drop in small system defaults (land in /usr/etc at runtime).
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  # Keep the host small but productive in TTY/Wayland terminals.
  - type: dnf
    repos:
      copr:
        - atim/starship
    install:
      packages:
        - helix         # TUI editor on the host
        - nu            # Nushell
        - starship      # Shell prompt
        - zoxide        # Smarter cd
        - git
        - ripgrep
        - fd-find
        - wireshark-cli # tshark + dumpcap
        - tcpdump
        - nmap
        - foot          # Tightweight Wayland terminal.
    remove:
      packages:
        # Removing firefox in favor of the Zen browser flatpak.
        - firefox # "firefox" is the main package.
        - firefox-langpacks # Also remove firefox dependency (not required for all packages, this is a special case).

  - type: default-flatpaks
    # If no repo information is specified, Flathub will be used by default.
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false).
        scope: system
        install: # System flatpaks we want all users to have and not remove.
          - app.zen_browser.zen
          - org.gnome.Loupe
          - com.visualstudio.code
          - com.github.tchx84.Flatseal
          - io.github.flattool.Warehouse
          - org.wireshark.Wireshark # The flatpak itself does not support capture, but it’s possible to pipe tshark. 
      - scope: user # Also add Flathub user repo, but no user packages.

  # Developer fonts.
  - type: fonts
    fonts:
      nerd-fonts:
        - JetBrainsMono
        - FiraCode
        - NerdFontsSymbolsOnly

  # Provide ujust commands for provisioning dev container(s).
  - type: justfiles

  - type: chezmoi
    disable-init: true
    all-users: false
    repository: "https://github.com/CBenoit/dotfiles"
    file-conflict-policy: skip

  # (Optional) If you need NVIDIA/other kernel modules later:
  # - type: akmods
  #   nvidia-driver: nvidia-open
  #   install: []

  - type: signing # This sets up the proper policy & signing files for signed images to work fully.
