anchor_to_edges: true
position: top
height: 32

start:
  - type: "volume"
    format: "{icon} {percentage}%"

  - type: sys_info
    format:
      - "| 　{cpu_percent}% | 　{memory_used}/{memory_total}G"
    interval:
      memory: 30
      cpu: 5

center:
  - type: focused
    truncate:
      mode: end
      max_length: 60

end:
  - type: clipboard
    max_items: 3
    truncate:
      mode: end
      length: 50

  - type: network_manager

  - type: bluetooth

  # Date and time in ISO format (YYYY/MM/DD HH:mm).
  - type: clock
    format: "%Y/%m/%d %H:%M"

  # System tray.
  # Hide when empty and collapse into a single icon when space is constrained.
  # This module shows SNI icons.
  - type: tray
    hide_when_empty: true
    collapse_when_hidden: true

  # Battery status. Automatically hides itself when no battery is present.
  - type: battery

  - type: notifications
