anchor_to_edges: true
position: top

start:
  # Music / sound player control.
  # Use MPRIS via playerctl to control any active media player.
  # The truncate section limits the displayed title length.
  - type: music
    player_type: mpris
    truncate:
      mode: end
      max_length: 40

  - type: "volume"
    format: "{icon} {percentage}%"

  - type: sys_info
    format:
      -  {cpu_percent}%  {memory_used:.1f}G/{memory_total:.1f}G
      - 󰋊 {disk_used#T@/:.1} / {disk_total#T@/:.1} TB ({disk_percent@/}%) | {disk_read} / {disk_write} MB/s
      - 󰓢 {net_down@enp39s0} / {net_up@enp39s0} Mbps
      - 󰥔 {uptime}
    interval:
      memory: 30
      cpu: 5
      disks: 300
      networks: 3

  # Battery status. Automatically hides itself when no battery is present.
  - type: battery

center:
  - type: focused
    truncate:
      mode: end
      max_length: 60

end:
  - type: clipboard
    max_items: 3
    truncate:
      mode: end
      length: 50

  - type: network_manager

  - type: bluetooth

  # Date and time in ISO format (YYYY/MM/DD HH:mm).
  - type: clock
    format: "%Y/%m/%d %H:%M"

  # System tray.
  # Hide when empty and collapse into a single icon when space is constrained.
  # This module shows SNI icons.
  - type: tray
    hide_when_empty: true
    collapse_when_hidden: true
