anchor_to_edges: true
position: bottom
layer: top
height: 28

start:
  - type: "script"
    class: weather
    cmd: "/etc/xdg/ironbar/scripts/weather"
    mode: 'poll'
    interval: 600000

  - type: "volume"
    format: "{icon} {percentage}%"

  - type: sys_info
    format:
      - "{cpu_percent}% "
      - "{memory_percent}% "
    interval:
      cpu: 5
      memory: 30

center:
  - type: focused
    truncate:
      mode: end
      max_length: 50

end:
  - type: clipboard
    max_items: 3
    truncate:
      mode: end
      length: 50

  - type: network_manager

  - type: bluetooth

  # Date and time in ISO format (YYYY/MM/DD HH:mm).
  - type: clock
    format: "%Y/%m/%d %H:%M"
    locale: "en_DK.UTF-8" # ISO-style.

  # System tray.
  # Hide when empty and collapse into a single icon when space is constrained.
  # This module shows SNI icons.
  - type: tray
    hide_when_empty: true
    collapse_when_hidden: true

  # Battery status. Automatically hides itself when no battery is present.
  - type: battery

  - type: notifications
